### ISSUE TITLE
Are multiple entities in the same driver planned for future versions?

### ISSUE THREAD

**Issue by dodger010** [bphillips09/Control4-HA-Coordinator#6]
Hi,

First, thank you for creating such a great and useful set of C4 & HA drivers. I've been able to integrate the Aqara FP2 sensor and combine the zones for motion sensors using the contact connection. For the Aqara FP2, it may be quite useful to have multiple binary entities supported for all respective zones, where one driver could then connect to multiple entities and connections. 

I was curious if combining multiple entities and allowing multiple C4 connections on the same driver may be considered in future releases? It may help consolidate drivers when using one sensor with multiple entities. There so many great sensors that combine temp, humidity, PIR & mmwave measurements so neat how all of these can be combined for programming.

The mmwave ones are interesting since they allow measurements to be taken for distance, so using your generic driver, along with distance data, it helps contribute to distance programming. I have been testing it in our garage with parking, where certain distances turns our lights red and green for visual warning. Control4 does not really have any "measurement" drivers, so using variables with programming seems like a good direction to go. So pretty neat how your drivers help integrate these kind of features.

I would be happy to beta test and provide feedback. :)

Kind regards,

**Comment by dacorn** [comment]
I agree with this request. This would be a huge addition to your driver package. I would also pay to have this done. Presence detection would be a huge feature to have in C4.  I personally have built my our using the LD2450 mmWave sensor but operates exactly the same as the Aqara FP2. (Only better)

**Comment by dodger010** [comment]
> I agree with this request. This would be a huge addition to your driver package. I would also pay to have this done. Presence detection would be a huge feature to have in C4. I personally have built my our using the LD2450 mmWave sensor but operates exactly the same as the Aqara FP2. (Only better)

Hi dacorn,

Funny you mention the  LD2450 mmWave, I believe the Screek ones I'm using the have the LD2410C board. I may need to look at those LD2450, seem very interesting. I've tuned the Aqara ones fairly well, so they are pretty accurate, just misses people every once in a while in my biggest area. I've also reached out to the developer of the Advanced Lighting Timer and he was kind enough to add a up to a 10 second debounce in his recent beta, which I use in certain zones that people pass by, works well when it does. Pairing those 2 drivers together really helps with lighting occupancy. 

Once I got the height and zone areas worked out, they work well . I'm also using the everything presence sensor, but since that one has limited zone, its been limited at the moment.

Cheers

**Comment by bphillips09** [comment]
Hi @dodger010 and @dacorn - Apologies for the late reply. 

I agree that this functionality would be very useful especially when the device you want to connect is a multi-sensor.

The main issue is that device drivers for Control4 usually need to have their types specified in the driver code when the driver is built, with a few exceptions. For example, a device that supports temperature, humidity, luminance, motion, and presence would present in HA as a single device with 5 entities. This would be difficult to represent as a single generic driver in C4 as the driver would have to support all 5 of those proxy types and only work with that specific device, which is outside the scope of my HA drivers. 

If a user had a similar device with 4 sensors or 6 sensors or maybe 5 sensors but one of them is binary instead of generic, the device driver functionality would be limited. The approach I've gone with (using a different driver for each entity type) is the only way currently that users can add support for whichever entities they want to add without additional bloat or unwanted devices. 

One of the few exceptions I am referring to is Thermostats, where the Control4 proxy can query the device for what it can support and adjust the driver accordingly. This feature is only available with a select number of proxies in the C4 system, one of which is the thermostat proxy (i.e. if the thermostat supports scheduling, cooling, heating, fan modes, etc.). For other device types, this isn't really supported.

**Comment by dodger010** [comment]
> Hi @dodger010 and @dacorn - Apologies for the late reply.
> 
> I agree that this functionality would be very useful especially when the device you want to connect is a multi-sensor.
> 
> The main issue is that device drivers for Control4 usually need to have their types specified in the driver code when the driver is built, with a few exceptions. For example, a device that supports temperature, humidity, luminance, motion, and presence would present in HA as a single device with 5 entities. This would be difficult to represent as a single generic driver in C4 as the driver would have to support all 5 of those proxy types and only work with that specific device, which is outside the scope of my HA drivers.
> 
> If a user had a similar device with 4 sensors or 6 sensors or maybe 5 sensors but one of them is binary instead of generic, the device driver functionality would be limited. The approach I've gone with (using a different driver for each entity type) is the only way currently that users can add support for whichever entities they want to add without additional bloat or unwanted devices.
> 
> One of the few exceptions I am referring to is Thermostats, where the Control4 proxy can query the device for what it can support and adjust the driver accordingly. This feature is only available with a select number of proxies in the C4 system, one of which is the thermostat proxy (i.e. if the thermostat supports scheduling, cooling, heating, fan modes, etc.). For other device types, this isn't really supported.

Hi,

Thanks for your reply, that is understandable. The driver function works well and it makes sense how the driver coding is different and how they interact with each other. Considering all of this, I'm just happy there is some kind of GUI connection between the two without complex coding for end user. We really do appreciate it.

Thanks and take care! :)
